Completed HTML and CSS copy of Youtube
imahnama/Youtube-replica pull request #1
Opened 2020-02-17 15:50 UTC by ikraamg

2020-02-18 13:24 UTC, euqueme requested changes
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @ikraamg and @imahnama  :balloon: :lollipop: 

### Your project looks extremely professional claps to you for your impressive Readme and very descriptive pull request and commits :clap: :clap:  :clap:  also I see you have stickler on already :muscle: 

### There is still some work to do so let's work on it! :point_down: 

## Project Specifics

**Inline Styling**

- [ ] Please remove all inline styling as this should exist only in the CSS file I've commented your code :arrow_double_down: 

**Video**

- [ ] It shows the avatar of the user who uploaded the video

- Yours

![image](https://user-images.githubusercontent.com/52209067/74738210-0da99180-521c-11ea-8b6b-02d205dc0e53.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/74738268-29ad3300-521c-11ea-9409-d5640e3dc397.png)

## Element sizing

**Navbar**

- [ ] There is too much margin or padding on the left, the Youtube logo should be smaller, also put more space between the icons on the right and make the search bar wider

- Yours

![image](https://user-images.githubusercontent.com/52209067/74738983-92e17600-521d-11ea-8f50-3cbbac119ad0.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/74739016-a42a8280-521d-11ea-90d2-d0ebc500a81a.png)

**Video**

- [ ] The video should be bigger please follow the size when your browser is fully displayed in your computer screen, also it should have less padding and margin on the left and right(it should be closer to the sidebar)

- Yours

![image](https://user-images.githubusercontent.com/52209067/74739658-f3bd7e00-521e-11ea-8ccb-19f52f4d9ccf.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/74739720-1354a680-521f-11ea-9048-5014d9929e97.png)

**Sidebar**

- [ ] The thumbnails on the sidebar should be smaller.

- Yours

![image](https://user-images.githubusercontent.com/52209067/74739995-9fff6480-521f-11ea-9d95-fdb97f6ceebf.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/74740022-b0afda80-521f-11ea-8001-f274b497235b.png)

### That's it! :raised_hands: 

### Please :pray: keep up the good work, make these changes :memo:  and submit back for a code review when you are done :rocket: 

Happy Coding! :woman_technologist: 

Any questions? reach to me on slack **@ Maru**

PROJECT STATUS: REQUESTED CHANGES :vertical_traffic_light:

2020-02-18 13:24 UTC, euqueme commented on index.html
> +            height="200"
- [ ] put the width and height selectors in the CSS file as there should be no inline styling in the HTML file  (suggestion: put them in your **.side-images class**)

2020-02-18 13:24 UTC, euqueme commented on index.html
> +            height="200"
- [ ] put the width and height selectors in the CSS file as there should be no inline styling in the HTML file  (suggestion: put them in your **.side-images class**)

2020-02-18 13:24 UTC, euqueme commented on index.html
> +            height="200"
- [ ] put the width and height selectors in the CSS file as there should be no inline styling in the HTML file  (suggestion: put them in your **.side-images class**)

2020-02-18 13:24 UTC, euqueme commented on index.html
> +            height="200"
- [ ] put the width and height selectors in the CSS file as there should be no inline styling in the HTML file  (suggestion: put them in your **.side-images class**)

2020-02-18 13:24 UTC, euqueme commented on index.html
> +            height="200"
- [ ] put the width and height selectors in the CSS file as there should be no inline styling in the HTML file  (suggestion: put them in your **.side-images class**)

2020-02-18 13:24 UTC, euqueme commented on index.html
> +            height="200"
- [ ] put the width and height selectors in the CSS file as there should be no inline styling in the HTML file  (suggestion: put them in your **.side-images class**)

2020-02-18 13:24 UTC, euqueme commented on index.html
> +            height="200"
- [ ] put the width and height selectors in the CSS file as there should be no inline styling in the HTML file  (suggestion: put them in your **.side-images class**)

2020-02-18 13:24 UTC, euqueme commented on index.html
> +            height="200"
- [ ] put the width and height selectors in the CSS file as there should be no inline styling in the HTML file  (suggestion: put them in your **.side-images class**)

2020-02-18 15:05 UTC, euqueme requested changes
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hi team!! :handshake: 

### Thank you for doing all the changes there's only one thing left to do:

**Video is overlapping**

- [ ] The video overlaps with the sidebar please fix this

![image](https://user-images.githubusercontent.com/52209067/74748141-ab598c80-522d-11ea-8de9-d9fb26cba70f.png)

### That's all

Fix this and submit back for a code review

Happy coding! :woman_technologist: 

PROJECT STATUS: REQUESTED CHANGES :vertical_traffic_light:

2020-02-18 16:22 UTC, nikasulo requested changes
# Nice work team! @ikraamg :handshake: @imahnama :handshake: 
You did great building this out and implementing changes suggested by @euqueme :+1: Please note, however, that the subscribe button along with all surrounding buttons are now missing. Please rectify this and request another review.

#### [OPTIONAL]
Please consider comparing your navigation styling along with the styling of all other elements, especially buttons to those on the original page. Some improvements can be made :ok_hand: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

2020-02-19 06:14 UTC, davitomix commented
### **Pull Request under the review by David Elí [TSE].**

2020-02-19 06:32 UTC, davitomix commented
### **Status: Approved ✔️ 💯** 
Hi Team, Congratulations for your job!
It looks very good! 
You have successfully implemented changes requested from the previous reviewers!
**Let's merge the branch and move unto the next project. ⏭  😄**

**[TSE:  David Elí]** 👨‍💻 
Github: [@davitomix](https://github.com/davitomix)
Linkedin: [David Elí Martínez García](https://www.linkedin.com/in/davideligarcia/)

2020-02-19 15:48 UTC, merged